#!/usr/bin/env bash
#
# scripts/docs-build.sh — Build docs site via mdBook + Mermaid validation.
#
# AC1 (docs/harness/seed.yaml) Mermaid validation ladder:
#   1) mdbook-mermaid preprocessor   — client-side render, no syntax check
#   2) mdbook-mermaid-mmdr           — SSR, validates (not installed by default)
#   3) mermaid-cli (mmdc)            — install: npm i -g @mermaid-js/mermaid-cli
#
# Build output: book/ (gitignored).
#
# Skip validation with --no-validate or NO_MERMAID_VALIDATE=1.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# cargo-installed tools (mdbook, mdbook-mermaid)
export PATH="$HOME/.cargo/bin:$PATH"

# Self-check: required tools (fresh-clone friendly)
missing=()
command -v mdbook >/dev/null 2>&1         || missing+=("mdbook (cargo install mdbook)")
command -v mdbook-mermaid >/dev/null 2>&1 || missing+=("mdbook-mermaid (cargo install mdbook-mermaid)")
command -v python3 >/dev/null 2>&1        || missing+=("python3 (system package — used by SUMMARY.md generator)")

if [ "${NO_MERMAID_VALIDATE:-0}" != "1" ] && [ "${1:-}" != "--no-validate" ]; then
  command -v mmdc >/dev/null 2>&1         || missing+=("mmdc (npm install -g @mermaid-js/mermaid-cli)")
fi

if [ ${#missing[@]} -gt 0 ]; then
  echo "[docs-build] ERROR: required tools not found:"
  for m in "${missing[@]}"; do echo "  - $m"; done
  echo
  echo "[docs-build] One-line install all:"
  echo "  cargo install mdbook mdbook-mermaid && npm install -g @mermaid-js/mermaid-cli"
  echo "[docs-build] Or run the harness bootstrap skill (handles tooling)."
  exit 1
fi

# Regenerate mermaid runtime assets if missing (gitignored as 2.6MB blob)
if [ ! -f "$ROOT/mermaid.min.js" ] || [ ! -f "$ROOT/mermaid-init.js" ]; then
  echo "[docs-build] Installing mermaid runtime assets..."
  mdbook-mermaid install "$ROOT" >/dev/null
fi

# 1. Regenerate docs/SUMMARY.md from section whitelist + git ls-files.
#
# To add a new section: insert one line into SECTIONS below.
# Each section auto-indexes all tracked *.md files in docs/<dir>/, sorted by path.
# Link text = first H1 of the file (text before " — " or " - " stripped for nav clarity);
# falls back to filename stem if no H1 present.
# docs/README.md is reserved as the [Introduction] entry.
SECTIONS=(
  "architecture:Architecture"
  "harness:Harness Outputs"
  "rules:Internal Rules"
  "checklists:Internal Checklists"
  "templates:Templates"
)

python3 - "$ROOT" "${SECTIONS[@]}" <<'PY'
import pathlib, re, subprocess, sys

root = pathlib.Path(sys.argv[1])
sections = sys.argv[2:]

def tracked_md(rel_dir: str) -> list[pathlib.Path]:
    res = subprocess.run(
        ["git", "ls-files", f"docs/{rel_dir}/*.md"],
        cwd=root, capture_output=True, text=True, check=True,
    )
    return sorted(pathlib.Path(p) for p in res.stdout.splitlines() if p.strip())

def untracked_md(rel_dir: str) -> list[pathlib.Path]:
    res = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard", f"docs/{rel_dir}/*.md"],
        cwd=root, capture_output=True, text=True, check=True,
    )
    return sorted(pathlib.Path(p) for p in res.stdout.splitlines() if p.strip())

def link_title(path: pathlib.Path) -> str:
    try:
        text = (root / path).read_text(encoding="utf-8", errors="ignore")
    except FileNotFoundError:
        return path.stem
    m = re.search(r"^# +(.+?)\s*$", text, re.MULTILINE)
    if not m:
        return path.stem
    title = m.group(1).strip()
    # Strip subtitle after em-dash / en-dash / hyphen-with-spaces for nav clarity
    title = re.split(r"\s+[—–-]\s+", title, maxsplit=1)[0].strip()
    return title or path.stem

lines = ["# Summary", "", "[Introduction](README.md)", "", "---", ""]
for entry in sections:
    rel_dir, section_title = entry.split(":", 1)
    files = tracked_md(rel_dir)
    if not files:
        continue
    lines.append(f"# {section_title}")
    lines.append("")
    for f in files:
        rel_link = f.relative_to("docs").as_posix()
        lines.append(f"- [{link_title(f)}]({rel_link})")
    lines.append("")

lines.append(
    "<!--\n"
    "This file is auto-generated by scripts/docs-build.sh from a section whitelist\n"
    "+ git ls-files. Do not edit by hand — changes will be overwritten on next build.\n"
    "To add a section, edit the SECTIONS array in scripts/docs-build.sh.\n"
    "Local-only archives (docs/brainstorming/, docs/reviews/, docs/sum/) remain\n"
    "gitignored and are not indexed; the viewer surfaces only tracked content so\n"
    "fresh clones build cleanly.\n"
    "-->"
)

(root / "docs" / "SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"[docs-build] Regenerated docs/SUMMARY.md ({sum(len(tracked_md(e.split(':',1)[0])) for e in sections)} entries across {len(sections)} sections).")

# Warn on untracked .md inside whitelisted sections so users notice silent skips.
# --exclude-standard respects .gitignore (sum/, brainstorming/, reviews/ stay quiet).
untracked = []
for entry in sections:
    rel_dir = entry.split(":", 1)[0]
    untracked.extend(untracked_md(rel_dir))
if untracked:
    print(
        f"[docs-build] WARN: {len(untracked)} untracked .md in whitelisted sections — "
        "run 'git add' for them to appear in the sidebar:",
        file=sys.stderr,
    )
    for p in untracked:
        print(f"  - {p.as_posix()}", file=sys.stderr)
PY

# 2. mdbook build (preprocessor renders mermaid blocks client-side)
mdbook build

# 3. Mermaid syntax validation
if [ "${NO_MERMAID_VALIDATE:-0}" = "1" ] || [ "${1:-}" = "--no-validate" ]; then
  echo "[docs-build] Mermaid validation skipped."
  echo "[docs-build] Done. Output: $ROOT/book/"
  exit 0
fi

if ! command -v mmdc >/dev/null 2>&1; then
  echo "[docs-build] ERROR: mmdc not found — Mermaid syntax validation required."
  echo "[docs-build]        Install: npm install -g @mermaid-js/mermaid-cli"
  echo "[docs-build]        Or skip: NO_MERMAID_VALIDATE=1 bash scripts/docs-build.sh"
  exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# Extract mermaid blocks from docs/ and validate
python3 - "$tmpdir" <<'PY'
import re, sys, pathlib
tmpdir = pathlib.Path(sys.argv[1])
docs = pathlib.Path('docs')
n = 0
for md in docs.rglob('*.md'):
    text = md.read_text(encoding='utf-8', errors='ignore')
    for i, block in enumerate(re.findall(r'```mermaid\s*\n(.*?)\n```', text, re.DOTALL)):
        out = tmpdir / f'block-{n}.mmd'
        out.write_text(block, encoding='utf-8')
        # Stash source path next to the block for diagnostics
        (tmpdir / f'block-{n}.src').write_text(f'{md}:block#{i}', encoding='utf-8')
        n += 1
print(f'[docs-build] Extracted {n} mermaid block(s).')
PY

fail=0
shopt -s nullglob   # empty glob expands to nothing instead of literal
for mmd in "$tmpdir"/block-*.mmd; do
  src=$(cat "${mmd%.mmd}.src")
  if ! mmdc -i "$mmd" -o "$tmpdir/out.svg" --quiet >/dev/null 2>&1; then
    echo "[docs-build] FAIL: Mermaid syntax error in $src"
    echo "----"
    cat "$mmd"
    echo "----"
    fail=1
  fi
done

if [ "$fail" -eq 1 ]; then
  echo "[docs-build] Mermaid validation failed."
  exit 1
fi

echo "[docs-build] Mermaid OK."
echo "[docs-build] Done. Output: $ROOT/book/"
